export PATH=${PATH}:~/Library/Python/2.7/bin:~/bin
export EDITOR=vim
export CLICOLOR=1
export PS1="\u@\h:\W\$ "
export LESS="~ceFiMRswX"
set -o vi
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
