#!/bin/bash

# script to auto-update brew stuff
#
# 1: update
# 2: check outdated & iterate the updates
# 3: use "brew cu"
# 4: clean up

# 1: update
# if this doesn't work, nothing following will either
echo "Starting update check"
brew update || exit 1

# 2: check outdated & iterate the updates
brew upgrade

# 3: upgrade taps
brew upgrade --cask

# 4: clean up
brew cleanup
